version: '3'
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  client:
    build: ./client
    environment:
      REDIS_ADDRESS: redis:6379
    ports:
      - "8080:8080"
    depends_on:
      - redis